name: CI

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Check dependencies
      run: make install

    - name: Create necessary directories
      run: |
        mkdir -p $GITHUB_WORKSPACE/src/logs
        mkdir -p $GITHUB_WORKSPACE/src/web_app/uploads

    - name: Lint code
      run: make lint

    - name: Run tests
      run: make test

    - name: Deploy to Docker Hub
      if: github.ref == 'refs/heads/main'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker build -t nikholasmartins/personal-development-repo:latest .
        docker push nikholasmartins/personal-development-repo:latest

  clean_up:
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean up
      run: make clean